### 결측치 제거
- 리뷰가 없는 경우 Review 값들이 결측치로 저장
- 리뷰가 없는 상품들을 제거하기 위해 전처리 진행

In [3]:
import pandas as pd

df=pd.read_csv("lifestyle_reviews_finn.csv",encoding='utf-8-sig')
df.tail()

,Product,Review 1,Review 2,Review 3,Review 4,Review 5,Review 6,Review 7,Review 8,Review 9,...,Review 101,Review 102,Review 103,Review 104,Review 105,Review 106,Review 107,Review 108,Review 109,Review 110
117,나이키 에어 페가수스 2005,Super comfortable I grabbed soon as they arriv...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,나이키 이니시에이터,이 제품 색깔 네이버에서 찜하기 해놨는데 공앱에 들어와서 결제했어요 멤버쉽데이 할인...,I recently got a pair of Nike shoes with a 90s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,조던 스타디움 90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,나이키 에어맥스 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,나이키 에어 페가수스 2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Review가 모두 결측치일 경우 해당 행 제거

# df3.iloc[:, 1:] = df3.iloc[:, 1:].copy()
# df3.iloc[:,1:].dropna(axis=0,how='all',inplace=True)
df.dropna(axis=0, how='all', subset=df.columns[1:], inplace=True) # subset 사용
df.tail()

,Product,Review 1,Review 2,Review 3,Review 4,Review 5,Review 6,Review 7,Review 8,Review 9,...,Review 101,Review 102,Review 103,Review 104,Review 105,Review 106,Review 107,Review 108,Review 109,Review 110
113,나이키 에어맥스 누엑시스,"Incredibly comfortable and versatile, just doe...",Extremely light and comfortable.,Bought these for the gym and are very comforta...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,나이키 코트 비전 로우,단정하고 가격대도 착한 신발이요 반업추천!!#멤버데이즈리뷰이벤트,디자인이 맘에 들었어요정사이즈로 보면 되구요 착화감은 발형태에 짜라 다르겠지만 보통...,넘 맘에 들고요… 신발이 제발를 착 감싸주는것이 느낌이 좋습니다.,I saw comments about how it was a little narro...,"Love the look of these, but they feel small an...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,나이키 에어 모어 업템포 로우,별5개짜리 디자인인데뒷꿈치가 기존 업템포에 비해 많이 낮아서설렁하게 끈 묶으면걸을때...,뒤꿈치가 좁고 걸을때 잘 버껴짐.뛰수가 없음.신발 디자인은 굿입니다.사이즈는 정사이...,검흰 사이즈는 정사이즈화면상 AIR이 하얀색인줄 알았는데받아보니 실버색상 참고!이쁘...,I love the are more uptempo and the low for me...,The Nike Uptempo with its iconic design has al...,I wear these shoes daily and they fit so well!...,The Air More Uptempo Low is a striking sneaker...,The Nike uptempo low is comfortable and stylis...,Shoes fit true to size. They are basketball sh...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,나이키 에어 페가수스 2005,Super comfortable I grabbed soon as they arriv...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,나이키 이니시에이터,이 제품 색깔 네이버에서 찜하기 해놨는데 공앱에 들어와서 결제했어요 멤버쉽데이 할인...,I recently got a pair of Nike shoes with a 90s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# 인덱스 재정렬
df.reset_index(drop=True,inplace=True)
df.tail()

,Product,Review 1,Review 2,Review 3,Review 4,Review 5,Review 6,Review 7,Review 8,Review 9,...,Review 101,Review 102,Review 103,Review 104,Review 105,Review 106,Review 107,Review 108,Review 109,Review 110
94,나이키 에어맥스 누엑시스,"Incredibly comfortable and versatile, just doe...",Extremely light and comfortable.,Bought these for the gym and are very comforta...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,나이키 코트 비전 로우,단정하고 가격대도 착한 신발이요 반업추천!!#멤버데이즈리뷰이벤트,디자인이 맘에 들었어요정사이즈로 보면 되구요 착화감은 발형태에 짜라 다르겠지만 보통...,넘 맘에 들고요… 신발이 제발를 착 감싸주는것이 느낌이 좋습니다.,I saw comments about how it was a little narro...,"Love the look of these, but they feel small an...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,나이키 에어 모어 업템포 로우,별5개짜리 디자인인데뒷꿈치가 기존 업템포에 비해 많이 낮아서설렁하게 끈 묶으면걸을때...,뒤꿈치가 좁고 걸을때 잘 버껴짐.뛰수가 없음.신발 디자인은 굿입니다.사이즈는 정사이...,검흰 사이즈는 정사이즈화면상 AIR이 하얀색인줄 알았는데받아보니 실버색상 참고!이쁘...,I love the are more uptempo and the low for me...,The Nike Uptempo with its iconic design has al...,I wear these shoes daily and they fit so well!...,The Air More Uptempo Low is a striking sneaker...,The Nike uptempo low is comfortable and stylis...,Shoes fit true to size. They are basketball sh...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,나이키 에어 페가수스 2005,Super comfortable I grabbed soon as they arriv...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,나이키 이니시에이터,이 제품 색깔 네이버에서 찜하기 해놨는데 공앱에 들어와서 결제했어요 멤버쉽데이 할인...,I recently got a pair of Nike shoes with a 90s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.to_csv("../lifestyle_reviews_final.csv",encoding='utf-8-sig',index=False)

In [7]:
# 결측행 제거 함수
def nan_processing(df_ex):
    df_ex.dropna(axis=0, how='all', subset=df_ex.columns[1:], inplace=True) # subset 사용
    df_ex.reset_index(drop=True,inplace=True)

In [8]:
df2=pd.read_csv("jordan_reviews.csv",encoding='utf-8-sig')
df3=pd.read_csv("running_reviews.csv",encoding='utf-8-sig')
df_list=[df2,df3]
for i in df_list:
    nan_processing(i)

df2.to_csv("../jordan_reviews_final.csv",encoding='utf-8-sig',index=False)
df3.to_csv("../running_reviews_final.csv",encoding='utf-8-sig',index=False)

In [ ]:
basketball_reviews=pd.read_csv("basketball_reviews.csv",encoding='utf-8-sig')
gym_reviews=pd.read_csv("gym_reviews.csv",encoding='utf-8-sig')
soccer_reviews=pd.read_csv("soccer_reviews.csv",encoding='utf-8-sig')

df_list2=[
        ("basketball_reviews", basketball_reviews),
        ("gym_reviews", gym_reviews),
        ("soccer_reviews", soccer_reviews),
          ]
for name,df in df_list2:
    nan_processing(df)
    df.to_csv(f"../{name}_final.csv",encoding='utf-8-sig',index=False)